### PR TITLE
Update README.md file with easier to use instructions

### PR DESCRIPTION
**Pull request by StefanJum**
This will remove the running scripts and add the commands in the README file, rename the `config-*` files and add a `TLDR` section that summarises the setup.

### CODE REVIEW

**Review by mariasfiraiala — CHANGES_REQUESTED** [review]
Even though the README is descriptive enough, I'd still like to have the run scripts available. Simply because the launch commands are kinda long.

Otherwise, all good on my side.

**Comment by StefanJum** [comment]
Done @mariasfiraiala, thank you.

**Review by mariasfiraiala — APPROVED** [review]
Nice, thanks!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
