### PR TITLE
Add KraftKit configuration file for KraftCloud

### PR DESCRIPTION
**Pull request by razvand**
Add `kraft.cloud.yaml` configuration file to build and run for KraftCloud.

Build with:

```console
kraft build --kraftfile kraft.cloud.yaml -j $(nproc)
```

Run with:

```console
kraft run --kraftfile kraft.cloud.yaml --plat firecracker --initrd ./fs0 --log-type basic --log-level debug -- /script.sql
```

### CODE REVIEW

**Review by craciunoiuc — APPROVED** [review]
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

**Comment by StefanJum** [comment]
This will fail at runtime with
```
Powered by
o.   .o       _ _               __ _
Oo   Oo  ___ (_) | __ __  __ _ ' _) :_
oO   oO ' _ `| | |/ /  _)' _` | |_|  _)
oOo oOO| | | | |   (| | | (_) |  _) :_
 OoOoO ._, ._:_:_,\_._,  .__,_:_, \___)
      Prometheus 0.14.0~08bd4e5e-custom
-- warning: cannot find home directory; cannot read ~/.sqliterc
kraftcloud-x86_64_fc-x86_64: Error: unknown option: -
Use -help for a list of options.
```
I don't know if it is related to this pr, the build works fine, so we could merge it and leave it as an open issue.

**Review by marcrittinghaus — APPROVED** [review]
-

**Review by marcrittinghaus — CHANGES_REQUESTED** [review]
This has LIBUKMMAP which conflicts with requirements from lib-ukp-bin

**Comment by razvand** [comment]
> This has LIBUKMMAP which conflicts with requirements from lib-ukp-bin

@marcrittinghaus , fixed.

**Review by marcrittinghaus — APPROVED** [review]
Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

**Pull request closed without merging**
